#!/bin/sh

get_main_address() {
    case "$board" in
	tl-wdr3600|tl-wdr4300)
	    uci get wireless.radio1.macaddr
	    ;;
	*)
	    uci get wireless.radio0.macaddr
	    ;;
    esac
}

uci set network.freifunk.macaddr=$(get_main_address)
uci commit network
