#!/bin/sh


wait=3


wait_config_mode() {
	sleep $wait
	uci set 'ffhl.@wizard[0].enabled=1'
	uci commit ffhl
	reboot
}


if [ "$BUTTON" = wps ]; then
	case "$ACTION" in
		pressed)
			wait_config_mode &
			PID=$!
			echo $PID > /tmp/.wait_config_mode
			;;
		released)
			if [ -r /tmp/.wait_config_mode ]; then
				kill $(cat /tmp/.wait_config_mode)
				rm /tmp/.wait_config_mode
			fi
			;;
	esac
fi
