#!/bin/sh

. /lib/ar71xx.sh

local lan_ifname="$(uci get network.lan.ifname)"
local board="$(ar71xx_board_name)"

uci -q batch <<EOF
delete network.lan

set network.wan.type='bridge'
set network.wan.proto='dhcp'
set network.wan.accept_ra='0'
set network.wan.auto='1'

set network.freifunk='interface'
set network.freifunk.ifname='$lan_ifname bat0'
set network.freifunk.type='bridge'
set network.freifunk.proto='dhcp'
set network.freifunk.defaultroute='0'

set network.mesh='interface'
set network.mesh.proto='none'
set network.mesh.mtu='1528'

set network.mesh5='interface'
set network.mesh5.proto='none'
set network.mesh5.mtu='1528'
EOF

case "$board" in
tl-wr1043nd) # fix up duplicate mac addresses
	local oIFS="$IFS"; IFS=":"; set -- $(uci get wireless.radio0.macaddr); IFS="$oIFS"
	local b2mask=0x02

	local wanaddr=$(printf "%02x:%s:%s:%02x:%s:%02x" $(( 0x$1 | $b2mask )) $2 $3 $(( (0x$4 + 1) % 0x100 )) $5 $(( (0x$6 + 1) % 0x100 )) )
	local ffaddr=$(printf "%02x:%s:%s:%02x:%s:%02x" $(( 0x$1 | $b2mask )) $2 $3 $(( (0x$4 + 1) % 0x100 )) $5 $(( (0x$6 + 2) % 0x100 )) )

	uci set network.wan.macaddr="$wanaddr"
	uci set network.freifunk.macaddr="$ffaddr"
	;;
tl-wdr3600|\
tl-wdr4300)
	local oIFS="$IFS"; IFS=":"; set -- $(uci get wireless.radio1.macaddr); IFS="$oIFS"
	local b2mask=0x02

	local wanaddr=$(printf "%02x:%s:%s:%02x:%s:%02x" $(( 0x$1 | $b2mask )) $2 $3 $(( (0x$4 + 1) % 0x100 )) $5 $(( (0x$6 + 1) % 0x100 )) )
	local ffaddr=$(printf "%02x:%s:%s:%02x:%s:%02x" $(( 0x$1 | $b2mask )) $2 $3 $(( (0x$4 + 1) % 0x100 )) $5 $(( (0x$6 + 2) % 0x100 )) )

	uci set network.wan.macaddr="$wanaddr"
	uci set network.freifunk.macaddr="$ffaddr"
	;;
*)
	local baseif=$(echo $lan_ifname | sed -e 's/\..*//')
	local ffaddr=$(cat /sys/class/net/$baseif/address)
	uci set network.freifunk.macaddr=$ffaddr
	;;
esac

uci commit network
