#!/bin/sh

uci -q batch <<EOF
delete wireless.radio0.disabled
delete wireless.@wifi-iface[0]

set wireless.radio0.channel='1'
set wireless.radio0.htmode='HT40+'
set wireless.radio0.country='DE'

set wireless.wifi_freifunk='wifi-iface'
set wireless.wifi_freifunk.device='radio0'
set wireless.wifi_freifunk.network='freifunk'
set wireless.wifi_freifunk.mode='ap'
set wireless.wifi_freifunk.ssid='hamburg.freifunk.net'

set wireless.wifi_mesh='wifi-iface'
set wireless.wifi_mesh.device='radio0'
set wireless.wifi_mesh.network='mesh'
set wireless.wifi_mesh.mode='adhoc'
set wireless.wifi_mesh.ssid='f8:d1:11:87:52:2e'
set wireless.wifi_mesh.bssid='f8:d1:11:87:52:2e'
set wireless.wifi_mesh.mcast_rate='12000'

commit wireless
EOF
