#!/bin/sh

local lan_ifname="$(uci get network.lan.ifname)"

uci -q batch <<EOF
delete network.lan

set network.wan.type='bridge'
set network.wan.proto='dhcp'
set network.wan.accept_ra='0'
set network.wan.auto='1'

set network.freifunk='interface'
set network.freifunk.ifname='$lan_ifname bat0'
set network.freifunk.type='bridge'
set network.freifunk.proto='dhcp'
set network.freifunk.gateway='0.0.0.0'

set network.mesh='interface'
set network.mesh.proto='none'
set network.mesh.mtu='1528'

commit network
EOF
