#!/bin/sh /etc/rc.common

START=12


config_mode_iface=eth0
config_mode_addr=192.168.1.1
config_mode_plen=24

config_mode_dnsname=freifunk
config_mode_dhcp_range=192.168.1.2,192.168.1.254

check_enabled() {
	config_get enabled "$1" enabled

	if [ "$enabled" ]; then
		export enabled
	fi
}

start() {
	enabled=0
	config_load ffhl
	config_foreach check_enabled wizard

	if [ "$enabled" = '1' ]; then
		ip addr add $config_mode_addr/$config_mode_plen dev $config_mode_iface
		ip link set up dev $config_mode_iface

		/etc/init.d/telnet start
		/etc/init.d/dropbear start
		/etc/init.d/uhttpd start
		/etc/init.d/led start

		echo "$config_mode_addr $config_mode_dnsname" > /tmp/hosts.config_mode
		dnsmasq -h -H /tmp/hosts.config_mode -R -F interface:$config_mode_iface,$config_mode_dhcp_range -l /tmp/dhcp.leases -O option:router

		. /etc/diag.sh
		get_status_led
		status_led_set_timer 1000 300

		# block further boot
		while true; do sleep 1; done
	fi
}
