#!/bin/sh /etc/rc.common

export SERVICE_NAME=visibility_hack

START=50

SERVICE_USE_PID=1
CRONTABS=/lib/freifunk/visibility_hack_crontabs/

start () {
        [ -z "$(ls $CRONTABS)" ] && exit 1
        service_start /usr/sbin/crond -c $CRONTABS
}

stop() {
        service_stop /usr/sbin/crond
}

